=== ebu/ame-cards/schema/FIMS-AME.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 sp2 (x64) (http://www.altova.com) by Alberto Messina (RAI - Radiotelevisione Italiana) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="FIMSAMECards">
		<xs:annotation>
			<xs:documentation>Comment describing your root
      element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AMECard" type="AMECardType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AMECardType">
		<xs:sequence>
			<xs:element name="CardID" type="xs:anyURI"/>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Audio"/>
						<xs:enumeration value="Video"/>
						<xs:enumeration value="Text"/>
						<xs:enumeration value="Multimodal"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Status">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="draft"/>
						<xs:enumeration value="published"/>
						<xs:enumeration value="publisheable"/>
						<xs:enumeration value="finalreview"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Editor" type="xs:string"/>
			<xs:element name="Alias" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Tag" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Definition" type="xs:string"/>
			<xs:element name="Reference" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Example" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Remarks" minOccurs="0"/>
			<xs:element name="Parameters">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Inputs">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Input" type="inputParameterType" minOccurs="0" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="Outputs">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Output" type="outputParameterType" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="CapabilityGroup" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Capability" type="capabilityType" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="parameterType" abstract="true">
		<xs:sequence>
			<xs:element name="Name" type="xs:NMTOKEN"/>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="controlled vocabulary"/>
						<xs:enumeration value="xml"/>
						<xs:enumeration value="text"/>
						<xs:enumeration value="URL"/>
						<xs:enumeration value="float"/>
						<xs:enumeration value="integer"/>
						<xs:enumeration value="boolean"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Representation" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Unit" minOccurs="0"/>
			<xs:element name="Definition" type="xs:string" minOccurs="0"/>
			<xs:element name="Comment" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="mandatory" type="xs:boolean" default="false"/>
	</xs:complexType>
	<xs:complexType name="inputParameterType">
		<xs:complexContent>
			<xs:extension base="parameterType">
				<xs:sequence>
					<xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="outputParameterType">
		<xs:complexContent>
			<xs:extension base="parameterType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="capabilityType">
		<xs:sequence>
			<xs:element name="Values">
				<xs:simpleType>
					<xs:union memberTypes="xs:anyURI xs:string"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="capabilityElement"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Unit" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="capabilityElement">
		<xs:restriction base="xs:string">
			<xs:enumeration value="supported audio formats"/>
			<xs:enumeration value="supported audio codec"/>
			<xs:enumeration value="result type"/>
			<xs:enumeration value="supported languages"/>
			<xs:enumeration value="supported recording conditions"/>
			<xs:enumeration value="supported speech types"/>
			<xs:enumeration value="supported video formats"/>
			<xs:enumeration value="supported video codec"/>
			<xs:enumeration value="supported image formats"/>
			<xs:enumeration value="supported text formats"/>
			<xs:enumeration value="supported scripts"/>
			<xs:enumeration value="supported object classes"/>
			<xs:enumeration value="supported speaker classes"/>
			<xs:enumeration value="recognisable text types"/>
			<xs:enumeration value="minimum text size"/>
			<xs:enumeration value="minimum object size"/>
			<xs:enumeration value="supported genres"/>
			<xs:enumeration value="supported modalities"/>
			<xs:enumeration value="supported descriptor sizes"/>
			<xs:enumeration value="activity adaptivity supported"/>
			<xs:enumeration value="extracting images supported"/>
			<xs:enumeration value="supported music genres"/>
			<xs:enumeration value="supported motion types"/>
			<xs:enumeration value="supported shot transition types"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ebu/ame-cards/cards/A008_AudioClassification.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <AMECard>
    <CardID>A008</CardID>

    <Name>Audio Classification</Name>

    <Type>Audio</Type>

    <Status>draft</Status>

    <Editor>Werner</Editor>

    <Definition>Determine if an audio segment represents a specified/one from a list of specified concept class(es).</Definition>

    <Parameters>
      <Inputs>
        <Input mandatory="true">
          <Name>ClassesToDetect</Name>
          <Type>controlled vocabulary</Type>
          <Representation>List of identifiers of classes to be detected</Representation>
        </Input>
        <Input>
          <Name>ModelToUse</Name>
          <Type>URL</Type>
          <Definition>If applicable, audio model to use for detection.</Definition>
        </Input>
      </Inputs>

      <Outputs>
        <Output mandatory="true">
          <Name>Classification</Name>
          <Type>xml</Type>
          <Representation>urn:mpeg:mpeg7:part5:SegmentType urn:mpeg:mpeg7:part5:StructuredAnnotationType</Representation>
          <Definition>Per object class, a list of time indexed regions</Definition>
        </Output>
        <Output>
          <Name>Confidence</Name>
          <Type>float</Type>
          <Definition>Confidence of the result (per detected instance)</Definition>
        </Output>
      </Outputs>
    </Parameters>

    <CapabilityGroup name="input formats">
      <Capability>
        <Values>urn:xyz</Values>

        <Type>supported audio formats</Type>
      </Capability>
    </CapabilityGroup>
  </AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/A006_AutomaticSpeechRecognition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 sp2 (x64) (http://www.altova.com) by Alberto Messina (RAI - Radiotelevisione Italiana) -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>A006</CardID>
		<Name>Automatic Speech Recognition</Name>
		<Type>Audio</Type>
		<Status>draft</Status>
		<Editor>Mike</Editor>
		<Definition>The translation of spoken words (from an audio fragment) into written text</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>RecordingCondition</Name>
					<Type>controlled vocabulary</Type>
				</Input>
				<Input>
					<Name>InlineDIctionaryExtension</Name>
					<Type>text</Type>
				</Input>
				<Input>
					<Name>RemoteDIctionaryExtension</Name>
					<Type>URL</Type>
				</Input>
				<Input>
					<Name>Language</Name>
					<Type>controlled vocabulary</Type>
					<Representation>http://iso.ch/languages.xml - TO BE FIXED</Representation>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>Transcript</Name>
					<Type>xml</Type>
					<Representation>urn:mpeg:mpeg7:part5:TextAnnotationType</Representation>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="audioCapabilityGroupType">
			<Capability xsi:type="audioLanguageCapabilityType">
				<Values>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Values>
				<Type>http://ebu.io/fims/ame/capabilities/audio/language</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="audioCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:AudioCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/audio</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="audioFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/audio</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="genericCapabilityGroupType" type="ASR">
			<Capability xsi:type="genericCapabilityType">
				<Values>urn:ebu:metadata-cs:SpeechTypeCS</Values>
				<Type>supported speech types</Type>
			</Capability>
			<Capability xsi:type="genericCapabilityType">
				<Values>urn:jhfkjsdhs</Values>
				<Type>supported recording conditions</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/M003_Mood-AffectiveClassification.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>M003</CardID>
		<Name>Mood/affective classification</Name>
		<Type>Multimodal</Type>
		<Status>draft</Status>
		<Editor>Lauri</Editor>
		<Definition>Classify the affective/emotional content of a multimedia item by assigning one or more class labels, or a score for one or more dimensions (e.g., valence and arousal; bpm for music; ...). If segmentation is given as input parameter, classification is done for each segment individually.</Definition>
		<Parameters>
			<Inputs>
				<Input mandatory="true">
					<Name>ClassesDatabase</Name>
					<Type>URL</Type>
					<Definition>A database with the trained categories or dimensions to be identified</Definition>
				</Input>
				<Input>
					<Name>InputSegmentationXml</Name>
					<Type>xml</Type>
					<Representation>urn:mpeg:mpeg7:schema:2004:TemporalDecompositionType/urn:mpeg:mpeg7:schema:2004:AudiovisualSegmentType</Representation>
					<Definition>The timeline of segments with their start and end times.</Definition>
				</Input>
				<Input>
					<Name>InputSegmentationJson</Name>
					<Type>json</Type>
					<Representation>urn:mpeg:mpeg7:schema:2004:TemporalDecompositionType/urn:mpeg:mpeg7:schema:2004:AudiovisualSegmentType</Representation>
					<Definition>The timeline of segments with their start and end times.</Definition>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>ListOfClasses</Name>
					<Type>xml</Type>
				  <Definition>A list of categories that have been associated to the item, optionally together with a confidence value</Definition>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="audioFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/audio</Type>
			</Capability>
			<Capability xsi:type="videoFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/video</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="audioCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:AudioCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/audio</Type>
			</Capability>
			<Capability xsi:type="videoCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:VideoCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/video</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="textCapabilityGroupType">
			<Capability xsi:type="textLanguageCapabilityType">
				<Values>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/language</Type>
			</Capability>
			<Capability xsi:type="textScriptCapabilityType">
				<Values>urn:iso:std:iso:15924</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/script</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="audioCapabilityGroupType">
			<Capability xsi:type="audioLanguageCapabilityType">
				<Values>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Values>
				<Type>http://ebu.io/fims/ame/capabilities/audio/language</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="contentTypeCapabilityGroupType">
			<Capability xsi:type="modalityCapabilityType">
				<Values>urn:mpeg:mpeg7:cs:ContentCS:2001</Values>
				<Type>http://ebu.io/fims/ame/capabilities/modalities</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="genericCapabilityGroupType" type="ContentMoodDimensions">
			<Capability xsi:type="genericCapabilityType">
				<Values>urn:ebu:metadata-cs:ContentMoodDimensionCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/moods</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/T003_KeywordExtraction.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>T003</CardID>
		<Name>Keyword extraction</Name>
		<Type>Text</Type>
		<Status>draft</Status>
		<Editor>Lauri</Editor>
		<Definition>The identification of the most relevant words in a text.</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>Language</Name>
					<Type>controlled vocabulary</Type>
					<Representation>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Representation>
					<Definition>The language of the text source</Definition>
				</Input>
				<Input mandatory="false">
					<Name>OutputFormat</Name>
					<Type>controlled vocabulary</Type>
				</Input>
			</Inputs>
			<Outputs>
				<Output mandatory="true">
					<Name>UntimedKeywords</Name>
					<Type>xml</Type>
					<Type>json</Type>
					<Representation>https://www.w3.org/TR/annotation-model/#selectors</Representation>
					<Definition>A list of keywords, optionally for each the amount of occurrences and a confidence score</Definition>
				</Output>
				<Output mandatory="false">
					<Name>TimedKeywords</Name>
					<Type>xml</Type>
					<Type>json</Type>
					<Representation>urn:mpeg:mpeg7:part5:AudiovisualSegmentType/urn:mpeg:mpeg7:schema:2004:TextAnnotationType</Representation>
					<Definition>A list of keywords, for each the amount of occurrences and a confidence score</Definition>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="textCapabilityGroupType">
			<Capability xsi:type="textScriptCapabilityType" >
				<Values>urn:iso:std:iso:15924</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/script</Type>
			</Capability>
			<Capability xsi:type="textLanguageCapabilityType" >
				<Values>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/language</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="textEncodingCapabilityType">
				<Values>https://www.iana.org/assignments/character-sets/character-sets.xhtml</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/textencoding</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="textFormatCapabilityType">
				<Values>https://www.iana.org/assignments/media-types/media-types.xhtml</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/text</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="resultCapabilityGroupType">
			<Capability xsi:type="resultCapabilityType" parameter="UntimedKeywords">
				<Type>http://ebu.io/fims/ame/capabilities/parameter</Type>
				<Formats>http://abc.com/formats</Formats>
				<Representations>http://abc.com/representations</Representations>
			</Capability>
			<Capability xsi:type="resultCapabilityType" parameter="TimedKeywords">
				<Type>http://ebu.io/fims/ame/capabilities/parameter</Type>
				<Formats>http://abc.com/formats</Formats>
				<Representations>http://abc.com/representations</Representations>
			</Capability>			
		</CapabilityGroup>		
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/V012_CopyDetectionMatching.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 sp2 (x64) (http://www.altova.com) by Alberto Messina (RAI - Radiotelevisione Italiana) -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>V012</CardID>
		<Name>Copy Detection (Matching)</Name>
		<Type>Video</Type>
		<Status>draft</Status>
		<Editor>Alberto</Editor>
		<Definition>Determine if a video segment is (near) identical to one of the video segments in a specified database. Common edit operations like colour adjustment, frame rate change or title overlay do not change the identity.</Definition>
		<Parameters>
			<Inputs>
				<Input mandatory="true">
					<Name>VideoFragment</Name>
					<Type>URL</Type>
					<Definition>The video clip (or possibly a part) to be checked for copy detection</Definition>
				</Input>
				<Input mandatory="true">
					<Name>MinimumMatchingDuration</Name>
					<Type>integer</Type>
					<Unit>frames</Unit>
					<Definition>The minimum matching duration to be considered a valid match</Definition>
				</Input>
				<Input mandatory="true">
					<Name>DBIdentifier</Name>
					<Type>URL</Type>
					<Unit/>
					<Definition>The reference to the index database</Definition>
				</Input>
			</Inputs>
			<Outputs>
				<Output mandatory="true">
					<Name>MatchingReport</Name>
					<Type>xml</Type>
					<Definition>A structure containing pointers from parts of the input video to (parts of) indexed clips</Definition>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="videoFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/video</Type>
			</Capability>
			<Capability xsi:type="imageFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/image</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/V008_FaceDetection.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>V008</CardID>
		<Name>Face Detection</Name>
		<Type>Video</Type>
		<Status>draft</Status>
		<Editor>Werner</Editor>
		<Definition>Determine if there are one or more regions showing (part of) a human face, and report their approximate boundaries.</Definition>
		<Parameters>
			<Inputs>
				<Input mandatory="false">
					<Name>OutputFormat</Name>
					<Type>controlled vocabulary</Type>
				</Input>
				<Input>
					<Name>StructuredRegionOfInterest</Name>
					<Type>xml</Type>
					<Representation>urn:mpeg:mpeg7:schema:2004:MovingRegionType</Representation>
					<Definition>A region in which to perform the detection.</Definition>
				</Input>
				<Input>
					<Name>MinimumSize</Name>
					<Type>integer</Type>
					<Unit>pixels</Unit>
					<Definition>The minimum size of faces to be detected in pixels.</Definition>
					<DefaultValue>50</DefaultValue>
				</Input>
				<Input>
					<Name>MaximumSize</Name>
					<Type>integer</Type>
					<Unit>pixels</Unit>
					<Definition>The maximum size of faces to be detected in pixels.</Definition>
					<DefaultValue>500</DefaultValue>
				</Input>	
				<Input>
					<Name>ModelToUse</Name>
					<Type>URL</Type>
					<Definition>The model for detection to use, if applicable (e.g., force use of frontal or lateral models only).</Definition>
				</Input>
			</Inputs>
			<Outputs>
				<Output >
					<Name>Detection</Name>
					<Type>xml</Type>
					<Type>json</Type>
					<Representation>urn:mpeg:mpeg7:schema:2004:MovingRegionType/urn:mpeg:mpeg7:schema:2004:MovingRegionType</Representation>
					<Comment>The output regions where faces have been detected</Comment>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="detectionCapabilityGroupType">
			<Capability xsi:type="minDetectionSizeCapabilityType">
				<Values>integer</Values>
				<Type>http://ebu.io/fims/ame/capabilities/audio/language</Type>
				<Unit>pixels</Unit>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="videoFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/video</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="videoCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:VideoCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/video</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputCapabilityGroupType">
			<Capability xsi:type="inputCapabilityType" parameter="StructuredRegionOfInterest">
				<Type>http://ebu.io/fims/ame/capabilities/parameter</Type>
				<Formats>http://abc.com/formats</Formats>
				<Representations>http://abc.com/representations</Representations>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="resultCapabilityGroupType">
			<Capability xsi:type="resultCapabilityType" parameter="Detection">
				<Type>http://ebu.io/fims/ame/capabilities/parameter</Type>
				<Formats>http://abc.com/formats</Formats>
				<Representations>http://abc.com/representations</Representations>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/M006_GenreSubjectRecognitionTraining.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>M006</CardID>
		<Name>Genre/Subject Recognition (Training)</Name>
		<Type>Multimodal</Type>
		<Status>draft</Status>
		<Editor>Werner</Editor>
		<Definition>Training module for a genre/subject classification service</Definition>
		<Parameters>
			<Inputs>
				<Input mandatory="true">
					<Name>GenreClassificationTrainingData</Name>
					<Type>xml</Type>
					<Comment>Training data contains locators to training essence files and ground truth annotations to train</Comment>
				</Input>
				<Input mandatory="false">
					<Name>ModelIdentifier</Name>
					<Type>URL</Type>
					<Definition>The identifier of the model that shall be trained.</Definition>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>TrainedModel</Name>
					<Type>URL</Type>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="audioFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/audio</Type>
			</Capability>
			<Capability xsi:type="videoFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/video</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="audioCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:AudioCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/audio</Type>
			</Capability>
			<Capability xsi:type="videoCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:VideoCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/video</Type>
			</Capability>
			<Capability xsi:type="textEncodingCapabilityType">
				<Values>https://www.iana.org/assignments/character-sets/character-sets.xhtml</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/textencoding</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="textCapabilityGroupType">
			<Capability xsi:type="textLanguageCapabilityType">
				<Values>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/language</Type>
			</Capability>
			<Capability xsi:type="textScriptCapabilityType">
				<Values>urn:iso:std:iso:15924</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/script</Type>
			</Capability>
		</CapabilityGroup>
		
		<CapabilityGroup xsi:type="inputCapabilityGroupType">
			<Capability xsi:type="inputCapabilityType" parameter="GenreClassificationTrainingData">
				<Type>http://ebu.io/fims/ame/capabilities/parameter</Type>
				<Formats>http://abc.com/formats</Formats>
				<Representations>http://abc.com/representations</Representations>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/A014_MusicGenreClassification.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 sp2 (x64) (http://www.altova.com) by Alberto Messina (RAI - Radiotelevisione Italiana) -->
<FIMSAMECards xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty">
  <AMECard>
    <CardID>13</CardID>

    <Name>Music Genre Classification</Name>

    <Type>Audio</Type>

    <Status>draft</Status>

    <Editor>Mike</Editor>

    <Definition>Identifying the genre of a particular piece of music</Definition>

    <Parameters>
      <Inputs>
        <Input>
          <Name>GenresModel</Name>

          <Type>controlled vocabulary</Type>
        </Input>
      </Inputs>

      <Outputs>
        <Output>
          <Name>ListofGenres</Name>

          <Type>xml</Type>

          <Representation>urn:mpeg:mpeg7:part5:TextAnnotationType</Representation>
        </Output>
      </Outputs>
    </Parameters>

    <CapabilityGroup name="ASR types">
      <Capability>
        <Values>urn:oiweuowieru</Values>

        <Type>supported music genres</Type>
      </Capability>
    </CapabilityGroup>

    <CapabilityGroup name="input formats">
      <Capability>
        <Values>urn:cvds</Values>

        <Type>supported audio codec</Type>
      </Capability>

      <Capability>
        <Values>urn:sdhfsdjkfh</Values>

        <Type>supported audio formats</Type>
      </Capability>
    </CapabilityGroup>
  </AMECard>
</FIMSAMECards>
