=== ebu/ame-cards/schema/FIMS-AME.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 sp2 (x64) (http://www.altova.com) by Alberto Messina (RAI - Radiotelevisione Italiana) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="FIMSAMECards">
		<xs:annotation>
			<xs:documentation>Comment describing your root
      element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AMECard" type="AMECardType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AMECardType">
		<xs:sequence>
			<xs:element name="CardID" type="xs:anyURI"/>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Audio"/>
						<xs:enumeration value="Video"/>
						<xs:enumeration value="Text"/>
						<xs:enumeration value="Multimodal"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Status">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="draft"/>
						<xs:enumeration value="published"/>
						<xs:enumeration value="publisheable"/>
						<xs:enumeration value="finalreview"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Editor" type="xs:string"/>
			<xs:element name="Alias" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Tag" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Definition" type="xs:string"/>
			<xs:element name="Reference" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Example" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Remarks" minOccurs="0"/>
			<xs:element name="Parameters">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Inputs">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Input" type="inputParameterType" minOccurs="0" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="Outputs">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Output" type="outputParameterType" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="CapabilityGroup" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Capability" type="capabilityType" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="parameterType" abstract="true">
		<xs:sequence>
			<xs:element name="Name" type="xs:NMTOKEN"/>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="controlled vocabulary"/>
						<xs:enumeration value="xml"/>
						<xs:enumeration value="text"/>
						<xs:enumeration value="URL"/>
						<xs:enumeration value="float"/>
						<xs:enumeration value="integer"/>
						<xs:enumeration value="boolean"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Representation" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Unit" minOccurs="0"/>
			<xs:element name="Definition" type="xs:string" minOccurs="0"/>
			<xs:element name="Comment" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="mandatory" type="xs:boolean" default="false"/>
	</xs:complexType>
	<xs:complexType name="inputParameterType">
		<xs:complexContent>
			<xs:extension base="parameterType">
				<xs:sequence>
					<xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="outputParameterType">
		<xs:complexContent>
			<xs:extension base="parameterType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="capabilityType">
		<xs:sequence>
			<xs:element name="Values">
				<xs:simpleType>
					<xs:union memberTypes="xs:anyURI xs:string"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="capabilityElement"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Unit" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="capabilityElement">
		<xs:restriction base="xs:string">
			<xs:enumeration value="supported audio formats"/>
			<xs:enumeration value="supported audio codec"/>
			<xs:enumeration value="result type"/>
			<xs:enumeration value="supported languages"/>
			<xs:enumeration value="supported recording conditions"/>
			<xs:enumeration value="supported speech types"/>
			<xs:enumeration value="supported video formats"/>
			<xs:enumeration value="supported video codec"/>
			<xs:enumeration value="supported image formats"/>
			<xs:enumeration value="supported text formats"/>
			<xs:enumeration value="supported scripts"/>
			<xs:enumeration value="supported object classes"/>
			<xs:enumeration value="supported speaker classes"/>
			<xs:enumeration value="recognisable text types"/>
			<xs:enumeration value="minimum text size"/>
			<xs:enumeration value="minimum object size"/>
			<xs:enumeration value="supported genres"/>
			<xs:enumeration value="supported modalities"/>
			<xs:enumeration value="supported descriptor sizes"/>
			<xs:enumeration value="activity adaptivity supported"/>
			<xs:enumeration value="extracting images supported"/>
			<xs:enumeration value="supported music genres"/>
			<xs:enumeration value="supported motion types"/>
			<xs:enumeration value="supported shot transition types"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ebu/ame-cards/cards/V005_VisualObjectClassification.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) by Lauri Saarikoski (Yle - The Finnish Broadcasting Company) -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>V005</CardID>
		<Name>Object classification</Name>
		<Type>Video</Type>
		<Status>draft</Status>
		<Editor>Lauri</Editor>
		<Definition>Determine if there are one or more regions showing (part of) a specified/one from a list of specified object class(es), and report their approximate boundaries.</Definition>
		<Parameters>
			<Inputs>
				<Input mandatory="true">
					<Name>ClassesToDetect</Name>
					<Type>xml</Type>
					<Representation/>
				</Input>
				<Input mandatory="true">
					<Name>MinimumObjectSizeToDetect</Name>
					<Type>integer</Type>
					<Representation/>
					<Unit>pixels</Unit>
				</Input>
				<Input>
					<Name>ObjectModelToUse</Name>
					<Type>URL</Type>
					<Definition>If applicable, visual model to use for detection.</Definition>
				</Input>
				<Input>
					<Name>BoundingBox</Name>
					<Type>text</Type>
					<Definition>A bounding box, specified as space separated list of x,y,w,h in pixels.</Definition>
				</Input>
			</Inputs>
			<Outputs>
				<Output mandatory="true">
					<Name>DetectedRegions</Name>
					<Type>xml</Type>
					<Representation>urn:mpeg:mpeg7:part5:MovingRegionType</Representation>
					<Definition>Per object class, a list of time indexed regions</Definition>
				</Output>
				<Output>
					<Name>Confidence</Name>
					<Type>float</Type>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="genericCapabilityGroupType" type="ObjectClassification">
			<Capability xsi:type="genericCapabilityType" type="ObjectClasses">
				<Values>urn:oiweuowieru</Values>
				<Type>http://ebu.io/fims/ame/capabilities/supportedObjectClasses</Type>
			</Capability>
			<Capability xsi:type="genericCapabilityType" type="minimumSize">
				<Values>int</Values>
				<Type>http://ebu.io/fims/ame/capabilities/miniumObjectSizeInPixels</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="videoFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/video</Type>
			</Capability>
			<Capability xsi:type="imageFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/image</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="videoCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:VideoCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/video</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/TextTaggingTraining.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) by Lauri Saarikoski (Yle - The Finnish Broadcasting Company) -->
<!-- Input audio fragment not needed as input? -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>T008</CardID>
		<Name>Text tagging training</Name>
		<Type>Text</Type>
		<Status>draft</Status>
		<Editor>Lauri</Editor>
		<Definition>Training module for a text tagging system</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>InputTextFragment</Name>
					<Type>text</Type>
				</Input>
				<Input>
					<Name>ClassificationData</Name>
					<Type>xml</Type>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>WasTrainingSuccess</Name>
					<Type>text</Type>
					<Representation/>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup name="input formats">
			<Capability>
				<Values>urn:cvds</Values>
				<Type>supported text formats</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/V001_Low-levelVisualDescriptorExtraction.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Git4win/ame-cards/schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>V001</CardID>
		<Name>Low-level visual descriptor extraction</Name>
		<Type>Video</Type>
		<Status>draft</Status>
		<Editor>Masa</Editor>
		<Definition>Extract desriptors representing visual features of single frames or a group of frames (e.g. MPEG-7 dominant color, accent color, amount of motion color layout etc.)</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>DetectedDescriptor</Name>
					<Type>controlled vocabulary</Type>
				</Input>
				<Input>
					<Name>TemporalFrequency</Name>
					<Type>controlled vocabulary</Type>
				</Input>
				<Input>
					<Name>Resolution</Name>
					<Type>controlled vocabulary</Type>
				</Input>
				<Input>
					<Name>Others</Name>
					<Type>xml</Type>
					<Comment>parameters depend on the descriptor to be extracted, in this case how far should we mention? Is there any good descriptive solutions for this problem? </Comment>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>Descriptor</Name>
					<Type>xml</Type>
				</Output>
				<Output>
					<Name>DescriptorFile</Name>
					<Type>URL</Type>
				</Output>
				<Output>
					<Name>Others</Name>
					<Type>xml</Type>
					<Comment>Detected descriptor tends to have its own structual data such a timepoint, timedutaion, region of interest.... How can we handle this?</Comment>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup>
			<Capability>
				<Values>urn:hogehoge</Values>
				<Type>supported video formats</Type>
			</Capability>
			<Capability>
				<Values>urn:hogehoge</Values>
				<Type>result type</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/T001_POSTagging.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>T001</CardID>
		<Name>Part of speech tagging</Name>
		<Type>Text</Type>
		<Status>draft</Status>
		<Editor>Werner</Editor>
		<Definition>The allocation of categories and relationships of words in a sentence. E.g., verbs or nouns (plural/...).</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>Language</Name>
					<Type>controlled vocabulary</Type>
					<Representation>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Representation>
					<Definition>The language of the text source</Definition>
				</Input>
				<Input mandatory="false">
					<Name>OutputFormat</Name>
					<Type>controlled vocabulary</Type>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>TimedTaggedWords</Name>
					<Type>xml</Type>
					<Type>json</Type>
					<Representation>urn:tbd</Representation>
					<Definition>A list of tagged words, for each the disambiguated category, relationship with other words, confidence score</Definition>
				</Output>
				<Output>
					<Name>UntimedTaggedWords</Name>
					<Type>xml</Type>
					<Type>json</Type>
					<Representation>https://www.w3.org/TR/annotation-model/#selectors</Representation>
					<Definition>A list of tagged words, for each the disambiguated category, relationship with other words, confidence score</Definition>
				</Output>
				
			</Outputs>
		</Parameters>
		
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="textEncodingCapabilityType">
				<Values>https://www.iana.org/assignments/character-sets/character-sets.xhtml</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/textencoding</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="textFormatCapabilityType">
				<Values>https://www.iana.org/assignments/media-types/media-types.xhtml</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/text</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="textCapabilityGroupType">
			<Capability xsi:type="textLanguageCapabilityType">
				<Values>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/language</Type>
			</Capability>
			<Capability xsi:type="textScriptCapabilityType">
				<Values>urn:iso:std:iso:15924</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/script</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="genericCapabilityGroupType" type="POS">
			<Capability xsi:type="genericCapabilityType" >
				<Values>urn:oiweuowieruf</Values>
				<Type>supported categories for words</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="resultCapabilityGroupType">
			<Capability xsi:type="resultCapabilityType" parameter="TimedTaggedWords">
				<Type>http://ebu.io/fims/ame/capabilities/parameter</Type>
				<Formats>http://abc.com/formats</Formats>
				<Representations>http://abc.com/representations</Representations>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="resultCapabilityGroupType">
			<Capability xsi:type="resultCapabilityType" parameter="UntimedTaggedWords">
				<Type>http://ebu.io/fims/ame/capabilities/parameter</Type>
				<Formats>http://abc.com/formats</Formats>
				<Representations>http://abc.com/representations</Representations>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/T002_Lemmatization.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Werner Bailer (JOANNEUM RESEARCH) -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>T002</CardID>
		<Name>Lemmatization</Name>
		<Type>Text</Type>
		<Status>draft</Status>
		<Editor>Mike</Editor>
		<Definition>The identification of the most relevant words in a text.</Definition>
		<Parameters>
			<Inputs>
			</Inputs>
			<Outputs>
				<Output mandatory="true">
					<Name>StemmedWords</Name>
					<Type>xml</Type>
					<Representation>urn:xyz</Representation>
					<Definition>Each word in the input text in its stemmed form together with morphosyntactic information and a confidence value</Definition>
				</Output>
			</Outputs>
		</Parameters>

		<CapabilityGroup xsi:type="textCapabilityGroupType">
			<Capability xsi:type="textLanguageCapabilityType">
				<Values>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/language</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="textFormatCapabilityType">
				<Values>https://www.iana.org/assignments/media-types/media-types.xhtml</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/text</Type>
			</Capability>
		</CapabilityGroup>

	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/OpticalCharacterRecognition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 sp2 (x64) (http://www.altova.com) by Alberto Messina (RAI - Radiotelevisione Italiana) -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>V001</CardID>
		<Name>Optical Character Recognition</Name>
		<Type>Video</Type>
		<Status>draft</Status>
		<Editor>Werner</Editor>
		<Definition>Detection of regions containing overlaid text elements or text depicted in the scene, possibly moving over time. Run OCR on the identified text areas.</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>StructuredRegionOfInterest</Name>
					<Type>xml</Type>
					<Representation>urn:mpeg:mpeg7:schema:2004:MovingRegionType</Representation>
				</Input>
				<Input>
					<Name>BoundingBox</Name>
					<Type>text</Type>
					<Definition>A bounding box, specified as space separated list of x,y,w,h in pixels</Definition>
				</Input>
				<Input>
					<Name>MinimumTextDuration</Name>
					<Type>float</Type>
					<Unit>seconds</Unit>
					<DefaultValue>0.04</DefaultValue>
				</Input>
			</Inputs>
			<Outputs>
				<Output mandatory="true">
					<Name>Transcript</Name>
					<Type>xml</Type>
					<Representation>urn:mpeg:mpeg7:schema:2004:TextAnnotationType</Representation>
					<Representation>urn:mpeg:mpeg7:schema:2004:MovingRegionType</Representation>
					<Comment>The output must contain the detected text, and may contain regions</Comment>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup name="Text Types">
			<Capability>
				<Values>urn:oiweuowieru</Values>
				<Type>supported languages</Type>
			</Capability>
			<Capability>
				<Values>urn:sfsdjkh</Values>
				<Type>supported scripts</Type>
			</Capability>
			<Capability>
				<Values>urn:jhfkjsdhs</Values>
				<Type>recognisable text types</Type>
			</Capability>
			<Capability>
				<Values>urn:jhfkjsdhs</Values>
				<Type>minimum text size</Type>
				<Unit>pixel</Unit>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup name="input formats">
			<Capability>
				<Values>urn:cvds</Values>
				<Type>supported video formats</Type>
			</Capability>
			<Capability>
				<Values>urn:sdhfsdjkfh</Values>
				<Type>supported image formats</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/V019_ImageVideoDescription.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) by Lauri Saarikoski (Yle - The Finnish Broadcasting Company) -->
<!-- Should be renamed to Visual concept detection?-->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>V019</CardID>
		<Name>Image/Video description</Name>
		<Type>Video</Type>
		<Status>draft</Status>
		<Editor>Mike</Editor>
		<Definition>Sentence-based description of a visual content item</Definition>
		<Parameters>
			<Outputs>
				<Output mandatory="true">
					<Name>Description</Name>
					<Type>text</Type>
					<Comment>A textual description of the contents in the input image or video</Comment>
				</Output>
				<Output>
					<Name>Confidence</Name>
					<Type>float</Type>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup name="input formats">
			<Capability>
				<Values>urn:cvds</Values>
				<Type>supported video formats</Type>
			</Capability>
			<Capability>
				<Values>urn:sdhfsdjkfh</Values>
				<Type>supported image formats</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/M005_Genre_SubjectClassification.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>M004</CardID>
		<Name>Genre/Subject Classification</Name>
		<Type>Multimodal</Type>
		<Status>draft</Status>
		<Editor>Alberto</Editor>
		<Definition>Determine the genre or subject of an audiovisual essence (segment) using a specified list of options.</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>ClassesToDetect</Name>
					<Type>controlled vocabulary</Type>
				</Input>
				<Input>
					<Name>MaxClassToReport</Name>
					<Type>integer</Type>
				</Input>
				<Input>
					<Name>MinLikelihood</Name>
					<Type>integer</Type>
				</Input>
				<Input>
					<Name>InputFragmentData</Name>
					<Type>URL</Type>
				</Input>
				<Input>
					<Name>Model</Name>
					<Type>URL</Type>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>DetectedClassesAndLikelihood</Name>
					<Type>xml</Type>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="contentTypeCapabilityGroupType">
			<Capability xsi:type="modalityCapabilityType">
				<Values>urn:mpeg:mpeg7:cs:ContentCS:2001</Values>
				<Type>http://ebu.io/fims/ame/capabilities/modalities</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="audioFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/audio</Type>
			</Capability>
			<Capability xsi:type="videoFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/video</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>
