=== ebu/ame-cards/schema/FIMS-AME.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 sp2 (x64) (http://www.altova.com) by Alberto Messina (RAI - Radiotelevisione Italiana) -->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="FIMSAMECards">
		<xs:annotation>
			<xs:documentation>Comment describing your root
      element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AMECard" type="AMECardType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AMECardType">
		<xs:sequence>
			<xs:element name="CardID" type="xs:anyURI"/>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Audio"/>
						<xs:enumeration value="Video"/>
						<xs:enumeration value="Text"/>
						<xs:enumeration value="Multimodal"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Status">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="draft"/>
						<xs:enumeration value="published"/>
						<xs:enumeration value="publisheable"/>
						<xs:enumeration value="finalreview"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Editor" type="xs:string"/>
			<xs:element name="Alias" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Tag" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Definition" type="xs:string"/>
			<xs:element name="Reference" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Example" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Remarks" minOccurs="0"/>
			<xs:element name="Parameters">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Inputs">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Input" type="inputParameterType" minOccurs="0" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="Outputs">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Output" type="outputParameterType" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="CapabilityGroup" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Capability" type="capabilityType" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="name" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="parameterType" abstract="true">
		<xs:sequence>
			<xs:element name="Name" type="xs:NMTOKEN"/>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="controlled vocabulary"/>
						<xs:enumeration value="xml"/>
						<xs:enumeration value="text"/>
						<xs:enumeration value="URL"/>
						<xs:enumeration value="float"/>
						<xs:enumeration value="integer"/>
						<xs:enumeration value="boolean"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Representation" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Unit" minOccurs="0"/>
			<xs:element name="Definition" type="xs:string" minOccurs="0"/>
			<xs:element name="Comment" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="mandatory" type="xs:boolean" default="false"/>
	</xs:complexType>
	<xs:complexType name="inputParameterType">
		<xs:complexContent>
			<xs:extension base="parameterType">
				<xs:sequence>
					<xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="outputParameterType">
		<xs:complexContent>
			<xs:extension base="parameterType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="capabilityType">
		<xs:sequence>
			<xs:element name="Values">
				<xs:simpleType>
					<xs:union memberTypes="xs:anyURI xs:string"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Type">
				<xs:simpleType>
					<xs:restriction base="capabilityElement"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Unit" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="capabilityElement">
		<xs:restriction base="xs:string">
			<xs:enumeration value="supported audio formats"/>
			<xs:enumeration value="supported audio codec"/>
			<xs:enumeration value="result type"/>
			<xs:enumeration value="supported languages"/>
			<xs:enumeration value="supported recording conditions"/>
			<xs:enumeration value="supported speech types"/>
			<xs:enumeration value="supported video formats"/>
			<xs:enumeration value="supported video codec"/>
			<xs:enumeration value="supported image formats"/>
			<xs:enumeration value="supported text formats"/>
			<xs:enumeration value="supported scripts"/>
			<xs:enumeration value="supported object classes"/>
			<xs:enumeration value="supported speaker classes"/>
			<xs:enumeration value="recognisable text types"/>
			<xs:enumeration value="minimum text size"/>
			<xs:enumeration value="minimum object size"/>
			<xs:enumeration value="supported genres"/>
			<xs:enumeration value="supported modalities"/>
			<xs:enumeration value="supported descriptor sizes"/>
			<xs:enumeration value="activity adaptivity supported"/>
			<xs:enumeration value="extracting images supported"/>
			<xs:enumeration value="supported music genres"/>
			<xs:enumeration value="supported motion types"/>
			<xs:enumeration value="supported shot transition types"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ebu/ame-cards/cards/T005_Tokenisation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Werner Bailer (JOANNEUM RESEARCH) -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>T005</CardID>
		<Name>Tokenisation</Name>
		<Type>Text</Type>
		<Status>draft</Status>
		<Editor>Alberto</Editor>
		<Definition>The detection of words, phrases, symbols (tokens) in a text.</Definition>
		<Parameters>
			<Inputs>
				<!-- no input params, assuming the text is provided as a resource to the FIMS service
				<Input>
					<Name>InputText</Name>
					<Type>text</Type>
					<Representation>TBD, could also be XML</Representation>
					<Definition>The input text to be processed (required)</Definition>
				</Input>		
				-->
				<Input>
					<Name>POSResults</Name>
					<Type>xml</Type>
					<Definition>The results of POS tagging on the input text, where available</Definition>
				</Input>
			</Inputs>
			<Outputs>
				<Output mandatory="true">
					<Name>Tokens</Name>
					<Type>xml</Type>
					<Representation>urn:tbd</Representation>
					<Definition>list of detected tokens, possibly with confidence scores</Definition>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup name="Text Types">
			<Capability>
				<Values>urn:oiweuowieru</Values>
				<Type>supported languages</Type>
			</Capability>
			<Capability>
				<Values>urn:sfsdjkh</Values>
				<Type>supported scripts</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup name="input formats">
			<Capability>
				<Values>urn:cvds</Values>
				<Type>supported text formats</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/V020_ConceptDetection.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>V020</CardID>
		<Name>Concept detection</Name>
		<Type>Video</Type>
		<Status>draft</Status>
		<Editor>Lauri</Editor>
		<Definition>Determine if a video segment represents a specified/one from a list of specified concept class(es). A concept is visually represented by the content, but not a particular object. Examples are day/night, indoor/outdoor, rural, ... Also includes basic actions such as person walking, person greeting other person.</Definition>
		<Parameters>
			<Inputs>
				<Input mandatory="false">
					<Name>OutputFormat</Name>
					<Type>controlled vocabulary</Type>
				</Input>			
				<Input mandatory="true">
					<Name>ClassesToDetect</Name>
					<Type>xml</Type>
					<Representation/>
				</Input>
				<Input>
					<Name>ConceptModelToUse</Name>
					<Type>URL</Type>
					<Definition>If applicable, visual model to use for detection.</Definition>
				</Input>
				<Input>
					<Name>InputSegmentationXml</Name>
					<Type>xml</Type>
					<Representation>urn:mpeg:mpeg7:schema:2004:TemporalDecompositionType/urn:mpeg:mpeg7:schema:2004:AudiovisualSegmentType</Representation>
					<Definition>The timeline of segments with their start and end times.</Definition>
				</Input>
				<Input>
					<Name>InputSegmentationJson</Name>
					<Type>json</Type>
					<Representation>urn:mpeg:mpeg7:schema:2004:TemporalDecompositionType/urn:mpeg:mpeg7:schema:2004:AudiovisualSegmentType</Representation>
					<Definition>The timeline of segments with their start and end times.</Definition>
				</Input>
			</Inputs>
			<Outputs>
				<Output mandatory="true">
					<Name>DetectedConcepts</Name>
					<Type>xml</Type>
					<Type>json</Type>
					<Representation/>
					<Comment>Per concept class, a list of time segments, optionally with confidence scores for each detection.</Comment>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="videoFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/video</Type>
			</Capability>
			<Capability xsi:type="imageFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/image</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="videoCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:VideoCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/video</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="resultCapabilityGroupType">
			<Capability xsi:type="resultCapabilityType" parameter="DetectedConcepts">
				<Type>http://ebu.io/fims/ame/capabilities/parameter</Type>
				<Formats>http://abc.com/formats</Formats>
				<Representations>http://abc.com/representations</Representations>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/ASRSpeakerAdaptation.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>A0011</CardID>
		<Name>speaker adaptation of ASR</Name>
		<Type>Audio</Type>
		<Status>draft</Status>
		<Editor>Alberto</Editor>
		<Definition>Training an ASR engine on a particular speaker</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>InputAudioFragments</Name>
					<Type>URL</Type>
				</Input>
				<Input>
					<Name>FragmentsTranscription</Name>
					<Type>xml</Type>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>WasTrainingSuccess</Name>
					<Type>text</Type>
					<Representation/>
				</Output>
				<Output>
					<Name>AdaptedModelReference</Name>
					<Type>URL</Type>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup name="input formats">
			<Capability>
				<Values>urn:sfsklsdfs</Values>
				<Type>supported audio codec</Type>
			</Capability>
			<Capability>
				<Values>urn:sdhfsdjkfh</Values>
				<Type>supported audio formats</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/T006_TextLanguageIdentification.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>T006</CardID>
		<Name>Language identification (Text)</Name>
		<Type>Text</Type>
		<Status>draft</Status>
		<Editor>Werner</Editor>
		<Definition>The recognition of the language of a text</Definition>
		<Parameters>
			<Inputs>
				<Input mandatory="false">
					<Name>OutputFormat</Name>
					<Type>controlled vocabulary</Type>
				</Input>
			</Inputs>
			<Outputs>
				<Output mandatory="true">
					<Name>TextSegments</Name>
					<Type>xml</Type>
					<Type>json</Type>
					<Representation>urn:tbd</Representation>
					<Definition>A list segments with start and end position (time stamp or word count), together with a language identifier according to ISO 639-1, -2 or -3, and an optional confidence score.</Definition>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="textEncodingCapabilityType">
				<Values>https://www.iana.org/assignments/character-sets/character-sets.xhtml</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/textencoding</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="textFormatCapabilityType">
				<Values>https://www.iana.org/assignments/media-types/media-types.xhtml</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/text</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="textCapabilityGroupType">
			<Capability xsi:type="textLanguageCapabilityType">
				<Values>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/language</Type>
			</Capability>
			<Capability xsi:type="textScriptCapabilityType">
				<Values>urn:iso:std:iso:15924</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/script</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="resultCapabilityGroupType">
			<Capability xsi:type="resultCapabilityType" parameter="TextSegments">
				<Type>http://ebu.io/fims/ame/capabilities/parameter</Type>
				<Formats>http://abc.com/formats</Formats>
				<Representations>http://abc.com/representations</Representations>
			</Capability>
		</CapabilityGroup>		
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/M001_SceneStorySegmentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>M001</CardID>
		<Name>Scene/story segmentation</Name>
		<Type>Multimodal</Type>
		<Status>draft</Status>
		<Editor>Werner</Editor>
		<Definition>Segment an audiovisual segment into semantic temporal units, such as news stories, scenes, etc.</Definition>
		<Parameters>
			<Inputs>
				<Input mandatory="false">
					<Name>OutputFormat</Name>
					<Type>controlled vocabulary</Type>
				</Input>
				<Input>
					<Name>MinDuration</Name>
					<Type>float</Type>
					<Unit>seconds</Unit>
					<Definition>Minimum duration of a segment to be reported.</Definition>
					<DefaultValue>0</DefaultValue>
				</Input>
				<Input>
					<Name>MaxDuration</Name>
					<Type>float</Type>
					<Unit>seconds</Unit>
					<Definition>Maximium duration of a segment to be reported.</Definition>
					<DefaultValue>inf</DefaultValue>
				</Input>				
			</Inputs>
			<Outputs>
				<Output>
					<Name>Segmentation</Name>
					<Type>xml</Type>
					<Type>json</Type>
					<Representation>urn:mpeg:mpeg7:schema:2004:TemporalDecompositionType/urn:mpeg:mpeg7:schema:2004:AudiovisualSegmentType</Representation>
					<Definition>The timeline of segments with their start and end times.</Definition>
				</Output>
			
			</Outputs>
		</Parameters>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="audioFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/audio</Type>
			</Capability>
			<Capability xsi:type="videoFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/video</Type>
			</Capability>
			<Capability xsi:type="textFormatCapabilityType">
				<Values>https://www.iana.org/assignments/media-types/media-types.xhtml</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/text</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="audioCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:AudioCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/audio</Type>
			</Capability>
			<Capability xsi:type="videoCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:VideoCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/video</Type>
			</Capability>
			<Capability xsi:type="textEncodingCapabilityType">
				<Values>https://www.iana.org/assignments/character-sets/character-sets.xhtml</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/textencoding</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="contentTypeCapabilityGroupType">
			<Capability xsi:type="modalityCapabilityType">
				<Values>urn:mpeg:mpeg7:cs:ContentCS:2001</Values>
				<Type>http://ebu.io/fims/ame/capabilities/modalities</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="genericCapabilityGroupType" type="ContentGenres">
			<Capability xsi:type="genericCapabilityType">
				<Values>urn:ebu:metadata-cs:ContentGenreCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/genres</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="resultCapabilityGroupType">
			<Capability xsi:type="resultCapabilityType" parameter="Segmentation">
				<Type>http://ebu.io/fims/ame/capabilities/parameter</Type>
				<Formats>http://abc.com/formats</Formats>
				<Representations>http://abc.com/representations</Representations>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="textCapabilityGroupType">
			<Capability xsi:type="textLanguageCapabilityType">
				<Values>urn:iso:std:iso:639:-1 urn:iso:std:iso:639:-2</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/language</Type>
			</Capability>
			<Capability xsi:type="textScriptCapabilityType">
				<Values>urn:iso:std:iso:15924</Values>
				<Type>http://ebu.io/fims/ame/capabilities/text/script</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/AudioClassificationTraining.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) by Lauri Saarikoski (Yle - The Finnish Broadcasting Company) -->
<!-- Input audio fragment not needed as input? -->
<!-- alternative input types for ClassificationData? JSON? -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>A009</CardID>
		<Name>Audio classification training</Name>
		<Type>Audio</Type>
		<Status>draft</Status>
		<Editor>Lauri</Editor>
		<Definition>Training service for an audio classification system</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>InputAudioFragment</Name>
					<Type>URL</Type>
				</Input>
				<Input>
					<Name>ClassificationData</Name>
					<Type>xml</Type>
				</Input>
			</Inputs>
			<Outputs>
				<Output>
					<Name>WasTrainingSuccess</Name>
					<Type>text</Type>
					<Representation/>
				</Output>
			</Outputs>
		</Parameters>
		<CapabilityGroup name="input formats">
			<Capability>
				<Values>urn:cvds</Values>
				<Type>supported audio codec</Type>
			</Capability>
			<Capability>
				<Values>urn:sdhfsdjkfh</Values>
				<Type>supported audio formats</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/V004_DominantMotionEstimation.xml
<?xml version="1.0" encoding="UTF-8"?>
<FIMSAMECards xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty">
  <AMECard>
    <CardID>V004</CardID>

    <Name>Dominant Camera Motion Estimation</Name>

    <Type>Video</Type>

    <Status>draft</Status>

    <Editor>Mike</Editor>

    <Definition>Estimation of the dominant global motion in the video, typically the caused by camera motion and/or zoom (including virtual cameras).</Definition>

    <Parameters>
      <Inputs>
        <Input>
          <Name>MotionTypes</Name>

          <Type>xml</Type>

          <Representation>urn:xjksjiweuf</Representation>

          <Definition>The motion types that should be reported</Definition>
        </Input>

        <Input>
          <Name>MinimumMotion</Name>

          <Type>xml</Type>

          <Representation>urn:jdksfajsdlf; </Representation>

          <Definition>The minimum motion size (per type) to be reported</Definition>
        </Input>
      </Inputs>

      <Outputs>
        <Output mandatory="true">
          <Name>DominantMotions</Name>

          <Type>xml</Type>

          <Representation>urn:jdksfjwie</Representation>

          <Comment>Dominant set of motions and their amounts per
          segment</Comment>
        </Output>
      </Outputs>
    </Parameters>

    <CapabilityGroup name="dominant motion estimation">
      <Capability>
        <Values>urn:oiweuowieru</Values>

        <Type>supported motion types</Type>
      </Capability>
    </CapabilityGroup>

    <CapabilityGroup name="input formats">
      <Capability>
        <Values>urn:cvds</Values>

        <Type>supported video formats</Type>
      </Capability>
    </CapabilityGroup>
  </AMECard>
</FIMSAMECards>

=== ebu/ame-cards/cards/V015_InstanceSearchIndexing.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2017 sp2 (x64) (http://www.altova.com) by Alberto Messina (RAI - Radiotelevisione Italiana) -->
<FIMSAMECards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema/FIMS-AME.xsd">
	<AMECard>
		<CardID>V015</CardID>
		<Name>Instance search (Indexing)</Name>
		<Type>Video</Type>
		<Status>draft</Status>
		<Editor>Lauri</Editor>
		
		<Definition>Extract features from a video and index them in a database for later matching.</Definition>
		<Parameters>
			<Inputs>
				<Input>
					<Name>TargetDescriptorSize</Name>
					<Type>integer</Type>
					<Unit>bytes/second</Unit>
					<Definition>The target bitrate of the desccriptors to be extracted.</Definition>
				</Input>
				<Input mandatory="true">
					<Name>DBIdentifier</Name>
					<Type>URL</Type>
					<Definition>The identifier of the database in which the descriptors/fingerprints shall be indexed.</Definition>
				</Input>
			</Inputs>
			<Outputs>
				<Output mandatory="true">
					<Name>DBIdentifier</Name>
					<Type>URL</Type>
					<Definition>The identifier of the database in which the descriptors/fingerprints have been indexed.</Definition>
				</Output>
			</Outputs>
		</Parameters>
		<!--TODO: Descriptor sizes need clarification-->
		<CapabilityGroup xsi:type="genericCapabilityGroupType" type="descriptorSizes">
			<Capability type="supportedDescriptorSize">
				<Type>integer</Type>
				<Unit>bytes/second</Unit>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputFormatCapabilityGroupType">
			<Capability xsi:type="videoFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/video</Type>
			</Capability>
			<Capability xsi:type="imageFormatCapabilityType">
				<Values>urn:ebu:metadata-cs:FileFormatCS_2010</Values>
				<Type>http://ebu.io/fims/ame/capabilities/format/image</Type>
			</Capability>
		</CapabilityGroup>
		<CapabilityGroup xsi:type="inputCodecCapabilityGroupType">
			<Capability xsi:type="videoCodecCapabilityType">
				<Values>urn:ebu:metadata-cs:VideoCompressionCodeCS</Values>
				<Type>http://ebu.io/fims/ame/capabilities/codec/video</Type>
			</Capability>
		</CapabilityGroup>
	</AMECard>
</FIMSAMECards>
